const assert = require("node:assert/strict");
const fs = require("node:fs");

const html = fs.readFileSync("index.html", "utf8");
const script = fs.readFileSync("match.js", "utf8");
const seekingData = fs.readFileSync("seeking-teams.js", "utf8");
const contactConfig = fs.readFileSync("contact-config.js", "utf8");

assert.match(html, /SOCIAL LOGIN/, "social login flow is missing");
assert.match(html, /사용하실 계정으로 로그인하세요/, "participant-facing sign-in copy is missing");
assert.match(html, /확인된 서울 참가 기록을 따라/, "journey must use verified records rather than self-reporting");
assert.match(html, /프로필을 미리 준비해 두었어요/, "Survey-prepared profile guidance is missing");
assert.match(html, /Random ID는 자동 배정됩니다/, "automatic Random ID guidance is missing");
assert.equal((html.match(/data-avatar=/g) || []).length, 7, "optional character picker must include none plus six choices");
assert.equal((html.match(/data-journey-step=/g) || []).length, 5, "participant journey must show five clear stages");
assert.ok(!html.includes('id="status-form"'), "participant journey must not ask users to self-report confirmed status");
assert.match(html, /인증 후 운영팀이 참가 기록을 확인합니다/, "manual approval safety copy is missing");
assert.ok(!html.includes("data-demo-login"), "insecure demo login controls must be removed");
assert.match(html, /data-auth-provider="google"/, "Google auth control is missing");
assert.match(html, /data-auth-provider="naver"/, "Naver auth control is missing");
assert.ok(!html.includes('data-auth-provider="kakao"'), "Kakao must not be offered as a login provider");
assert.match(html, /Google로 계속하기/, "participant-facing Google sign-in label is missing");
assert.match(html, /Naver로 계속하기/, "participant-facing Naver sign-in label is missing");
assert.ok((html.match(/data-open-login/g) || []).length >= 3, "sign-in must be easy to reach from the main participant flow");
assert.match(html, /모집 중일 때만 허브 팀 목록에 표시됩니다/, "seeking-member rule is missing");
assert.match(html, /마지막 메시지 후 5일간 답변이 없으면 대화가 자동 종료됩니다/, "confirmed five-day inactivity policy is missing");
assert.match(html, /Team Owner/, "owner workspace is missing");
assert.match(html, /id="my-space"/, "role-based MY SPACE review section is missing");
assert.match(html, /id="sent-contact-log"/, "participant sent-message log is missing");
assert.match(html, /APPROVED TEAM OWNER/, "Team Owner case preview is missing");
assert.match(html, /현재 팀을 찾는 대원/, "participant discovery view is missing");
assert.match(html, /Team Owner에게 이메일 받기/, "participant email opt-in copy is missing");
assert.match(html, /우리 팀이 받은 관심/, "owner received-interest view is missing");
assert.match(script, /data-directory-view/, "team and participant directory switch is missing");
assert.match(html, /id="participant-contact-form"/, "Team Owner contact form is missing");
assert.match(html, /이메일 보내기/, "email relay action is missing");
assert.match(script, /recipientParticipantId/, "email relay must address participants by internal ID");
assert.match(script, /fetch\(contactEndpoint/, "Resend-ready relay endpoint call is missing");
assert.match(contactConfig, /provider: "resend"/, "Resend provider slot is missing");
assert.ok(!/api[_-]?key|secret/i.test(contactConfig), "contact config must not contain client-side secrets");
assert.equal((html.match(/class="check-mark"/g) || []).length, 3, "verified records must use three check icons");
assert.match(html, /id="team-group-bubbles"/, "five-group team finder is missing");
assert.match(html, /고정 자료 · 자동 갱신 준비 중/, "twice-daily sync schedule is missing");
assert.equal((seekingData.match(/seeking: true/g) || []).length, 15, "current official Seeking Members list must contain fifteen teams");

const catalog = fs.readFileSync("match-catalog.js", "utf8");
const challengeRows = [...catalog.matchAll(/\{ id: "[^"]+", number: \d+, title:/g)];
assert.equal(challengeRows.length, 14, "all 14 official 2026 challenge choices must be present");
assert.equal((catalog.match(/challengeIds:/g) || []).length, 5, "exactly five Seoul browsing groups are required");
assert.match(script, /length >= 3/, "challenge selection limit is missing");
assert.equal((html.match(/data-max="3"/g) || []).length, 2, "profile roles allow three choices");
assert.match(html, /id="owner-role-picker" data-max="5"/, "owner roles allow five choices");
assert.match(script, /currentRoles\.length} \/ 3/, "current role counter must use the three-choice limit");
assert.match(script, /desiredRoles\.length} \/ 3/, "desired role counter must use the three-choice limit");
assert.match(script, /members \+ openings > 6/, "NASA team-size guard is missing");
assert.match(script, /escapeHtml\(team\.name\)/, "team names must be escaped before rendering");
assert.match(script, /hostname\.endsWith\("\.spaceappschallenge\.org"\)/, "team links must stay on the official NASA Space Apps domain");
assert.match(script, /syncJourneyProgress/, "participant journey must update after profile and team actions");
assert.match(script, /syncAvatarUi/, "optional character choice must update the profile UI");
assert.match(script, /setupTeamGroupBubbles/, "five-group team finder behavior is missing");
assert.match(script, /selectedInGroup/, "selected challenge groups must track their selected items");
assert.match(script, /details\.open = false/, "challenge groups start collapsed");
assert.match(script, /aria-expanded/, "challenge groups expose expanded state");
assert.match(script, /challenge-source-link/, "official challenge source link must occupy the open grid cell");
assert.match(script, /NASA SPACE APPS OFFICIAL/, "official challenge link must use the full NASA Space Apps label");
assert.ok(!html.includes("이 분류는 탐색을 돕기 위한"), "duplicate classification note must be removed");
assert.ok(!script.includes("`${selectedCount} 선택`"), "visible per-group selected count must be removed");
const styles = fs.readFileSync("styles.css", "utf8");
assert.match(styles, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/, "desktop challenge groups must use a three-column grid");
assert.match(styles, /background: #fff2a8/, "selected challenges need a yellow highlight");
assert.match(styles, /#current-role-picker[\s\S]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/, "profile roles must use two rows of four on desktop");

console.log("team match checks: auth flow, 14 challenges, five groups, and owner safeguards passed");
